### ISSUE TITLE
Issue with connecting Cisco IOS device via SSH user

### ISSUE THREAD

**Issue by dpradhan119** [ansible/community#130]
Hi Team,

I have configured /etc/ansible/group_vars and my contents are  below.

ansible_ssh_user: username
ansible_ssh_pass: password
ansible_ssh_port: port

But while connection to CISCO ios device via SSH i am getting below error.
192.168.0.100 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh.",
    "unreachable": true

Thanks,
Deepak

**Comment by gundalow** [comment]
Hi, the `ansible/community` GitHub repo is for tracking improvements to the community.

Bug reports should go into https://github.com/ansible/ansible/issues

Asking for help should be done on `#ansible` on Freenode IRC, or on the Google Mailing Lists.

However in this case I believe the following may be useful pointers.


Create some `group_vars` for this type of machine/switch

```yaml
File: group_vars/ios.yaml

cli:
  host: "{{ inventory_hostname }}"
  username: "username"
  password: "password"
  transport: cli
```

Then in your task
```yaml
- name: test getting all facts
  ios_facts:
    provider: "{{ cli }}"
    gather_subset:
      - all
  register: result

```
