### ISSUE TITLE
Public Ansible Project Meeting Agenda - February 2018

### ISSUE THREAD

**Issue by thaumos** [ansible/community#296]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

When creating new agenda ensure `core` and `meeting_agenda` labels are set

**Comment by thaumos** [comment]
2018 - 02 - 06 Meeting:

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-06/ansible_core.2018-02-06-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-02-06/ansible_core.2018-02-06-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-06/ansible_core.2018-02-06-19.00.log.html

**Comment by maxamillion** [comment]
Should the `include_vars` action plugin failing when encountering a file of non-valid file extension be the expected behavior or is this a bug?

There were some disagreements about this in the past and I'd like consensus/clarification on it from the group.

https://github.com/ansible/ansible/issues/35745

**Comment by thaumos** [comment]
2018 - 02 - 08 Meeting:

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-08/ansible_core.2018-02-08-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-02-08/ansible_core.2018-02-08-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-08/ansible_core.2018-02-08-15.00.log.html

**Comment by sivel** [comment]
Discuss plans for 2.6, what our goals are, what that means for committers and the community.

**Comment by gundalow** [comment]
FortiOS and FortiGate
https://github.com/ansible/ansible/pull/33591#issuecomment-364775042
Would like feedback on this approach

**Comment by abadger** [comment]
Meeting ended Tue Feb 13 20:08:56 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-13/ansible_core.2018-02-13-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-02-13/ansible_core.2018-02-13-19.00.txt
 Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-13/ansible_core.2018-02-13-19.00.log.html

**Comment by gundalow** [comment]
Add ability to define filter macros https://github.com/ansible/ansible/issues/36130

**Comment by abadger** [comment]
Meeting ended Tue Feb 27 19:39:29 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-27/ansible_core.2018-02-27-18.59.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-02-27/ansible_core.2018-02-27-18.59.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-02-27/ansible_core.2018-02-27-18.59.log.html

**Comment by Im0** [comment]
Hoping to join and discuss PR's:  #36372 #37001
IRC Nick: Imo

**Comment by dagwieers** [comment]
I am looking for more feedback on https://github.com/ansible/ansible/pull/36901, @dharmabumstead proposed to do https://github.com/ansible/ansible/pull/36901#issuecomment-369757086 but I am not convinced this is the direction we want to take the documentation.

**Comment by dharmabumstead** [comment]
We appreciate your feedback and your contributions, @dagwieers. Community feedback is welcome and crucial, but ultimately any decisions about what goes into the documentation and how that information is presented falls to the Ansible documentation team.

**Comment by dagwieers** [comment]
Then maybe the documentation should be a product solemnly created by the Ansible documentation team.

**Comment by dagwieers** [comment]
@dharmabumstead Then let's make sure the Ansible documentation team ultimately makes the best decision !

**Comment by abadger** [comment]
Looking for input on whether we're okay not handling archives which specify an absolute path in unarchive (impacts whether this is an acceptable fix): https://github.com/ansible/ansible/pull/37048

**Comment by abadger** [comment]
Meeting ended Tue Mar  6 20:15:06 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-06/ansible_core_team_meeting.2018-03-06-19.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-03-06/ansible_core_team_meeting.2018-03-06-19.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-06/ansible_core_team_meeting.2018-03-06-19.06.log.html

**Comment by abadger** [comment]
From agaffney: Allow loading dirs from role defaults/vars https://github.com/ansible/ansible/pull/36357

**Comment by gundalow** [comment]
*Ansible 2.5.0 Release Candidate 2* is now available! Get it on PyPI: `pip install ansible==2.5.0rc2`, https://releases.ansible.com/ansible/, or GitHub. 
* This is likely to be the final Release Candidate, so please test, and raise issues on GitHub

**Comment by abadger** [comment]
[13:45:59] <zodbot> Meeting ended Tue Mar 13 20:45:59 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
[13:45:59] <zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-13/ansible_core_team_irc_meeting.2018-03-13-19.06.html
[13:45:59] <zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-03-13/ansible_core_team_irc_meeting.2018-03-13-19.06.txt
[13:45:59] <zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-13/ansible_core_team_irc_meeting.2018-03-13-19.06.log.html

**Comment by bcoca** [comment]
uneventful:

[11:17] <zodbot> Meeting ended Thu Mar 15 15:18:37 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
[11:17] <zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-15/ansible_core.2018-03-15-15.05.html
[11:17] <zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-03-15/ansible_core.2018-03-15-15.05.txt
[11:17] <zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-15/ansible_core.2018-03-15-15.05.log.html

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/22025

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/37883

**Comment by sieben** [comment]
https://github.com/ansible/ansible/pull/37638

**Comment by bcoca** [comment]
[15:48] <zodbot> Meeting ended Tue Mar 27 19:49:46 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
[15:48] <zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-27/ansible_core_team_meeting.2018-03-27-19.05.html
[15:48] <zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-03-27/ansible_core_team_meeting.2018-03-27-19.05.txt
[15:48] <zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-03-27/ansible_core_team_meeting.2018-03-27-19.05.log.html

**Comment by pilou-** [comment]
- https://github.com/ansible/ansible/pull/36651 (meanwhile an issue has been created: ansible/ansible#37506)
- ansible/ansible#38100: i am willing to fix that but what should be the behavior ? Should `ansible-config` always display plugins parameters ? Or should a new switch (`--plugin-type`) be added ? Should plugin type and name be mentioned for each plugin parameter ? Should uppercase be used for parameter names ? In the samples below, a 'regular' parameter (`DEFAULT_FORKS`) and a plugin parameter (`oc_cert_file`) are displayed:

  ```yaml
  DEFAULT_FORKS:
    default: 5
    description: Maximum number of forks Ansible will use to execute tasks on target
    hosts.
    env:
    - {name: ANSIBLE_FORKS}
    ini:
    - {key: forks, section: defaults}
    name: Number of task forks
    type: integer
  oc_cert_file:
    default: ''
    description: [Path to a certificate used to authenticate with the API.]
    env:
    - {name: K8S_AUTH_CERT_FILE}
    vars:
    - {name: ansible_oc_cert_file}
  ```
  Uppercase used for parameter name:
  ```yaml
  DEFAULT_FORKS:
    default: 5
    description: Maximum number of forks Ansible will use to execute tasks on target
    hosts.
    env:
    - {name: ANSIBLE_FORKS}
    ini:
    - {key: forks, section: defaults}
    name: Number of task forks
    type: integer
  OC_CERT_FILE:
    default: ''
    description: [Path to a certificate used to authenticate with the API.]
    env:
    - {name: K8S_AUTH_CERT_FILE}
    vars:
    - {name: ansible_oc_cert_file}
  ```
  Plugin type and name added:
  ```yaml
  DEFAULT_FORKS:
    default: 5
    description: Maximum number of forks Ansible will use to execute tasks on target
    hosts.
    env:
    - {name: ANSIBLE_FORKS}
    ini:
    - {key: forks, section: defaults}
    name: Number of task forks
    type: integer
  oc_cert_file:
    plugin_type: connection
    plugin_name: oc
    default: ''
    description: [Path to a certificate used to authenticate with the API.]
    env:
    - {name: K8S_AUTH_CERT_FILE}
    vars:
    - {name: ansible_oc_cert_file}
  ```
