### ISSUE TITLE
Improving Docker modules

### ISSUE THREAD

**Issue by gundalow** [ansible/community#379]
Issue to track ideas for docker modules.

May not need a full working group around Ansible & Docker, though there are some people doing good stuff and others wondering how to help.

* Update maintainers, do we want `team_docker`?
* Who would like to become part of `team_docker`?
* Identify gaps and priorities in testing, @felixfontein has been doing good work here
* What else?

Currently we have the following in [BOTMETA.yml](https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml)
```
  $modules/cloud/docker/:
    ignored: ThomasSteinbach
    notified: felixfontein
  $modules/cloud/docker/docker_container.py: $team_ansible felixfontein
  $modules/cloud/docker/docker_image.py: $team_ansible
  $modules/cloud/docker/docker_image_facts.py: $team_ansible
  $modules/cloud/docker/docker_network.py: olsaki
  $modules/cloud/docker/docker_service.py: $team_ansible
```
