### ISSUE TITLE
How to tag EC2_Customer_Gateway using playbook?

### ISSUE THREAD

**Issue by antarmy07** [ansible/community#470]
How do you create tags on ec2_customer_gateway from ansible playbook? I can't seem to find any solution for this.

COMPONENT NAME
EC2_CUSTOMER_GATEWAY

ANSIBLE VERSION
ansible 2.7.2

CONFIGURATION
 ```
- name: Create a new cgw
   ec2_customer_gateway:
    bgp_asn: 65000
    ip_address: XXXXXXXXX
    name: "XXXXXX"
    region: "{{ region }}"
   register: ds_cgw_result

 - name: modify CGW connection tags
   ec2_customer_gateway:
    state: present
    region: "{{ region }}"
    customer_gateway_id: "{{ ds_cgw_result.gateway.customer_gateway.customer_gateway_id }}"
    name: "XXXXXXX"
    tags:
      Environment: "{{ env }}"
      Type: "customer gateaway"
      Service: "XXXX"
      Component: "Networking"
      Department: "XXXX"
   register: local_cgw_mod_result 
```
OS / ENVIRONMENT
STEPS TO REPRODUCE
EXPECTED RESULTS
Tag to be created on the newly created CGW. The same method works for VGW and VPN.

ACTUAL RESULTS

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ec2_customer_gateway) module: customer_gateway_id, tags Supported parameters include: aws_access_key, aws_secret_key, bgp_asn, ec2_url, ip_address, name, profile, region, routing, security_token, state, validate_certs"}
`

This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project
