### ISSUE TITLE
vmware_guest: RC4122 /****.vmdk already exists

### ISSUE THREAD

**Issue by realged13** [ansible/community#472]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Issue**: When deploying a Centos7 template using vmware_guest, the action fails stating that the rfc4122.xxxxxxxx/******.vmdk already exists.  This issue does not occur in Ansible 2.7

**Ansible Version**:

```
ansible 2.8.0
  config file = /home/ansible28/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible28/lib/python2.7/site-packages/ansible
  executable location = /home/ansible28/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

Playbook:

```

---
- hosts: dc-vcenter
  gather_facts: false
  connection: local
  roles:
    - vmware

  vars_prompt:
    - name: "vcenter_username"
      prompt: "vCenterUsername"
    - name: "vcenter_password"
      prompt: "vCenter Password"
    - name: "vmware_hostname"
      prompt: "VM Hostname"
      private: no
    - name: "vm_ip"
      prompt: "Enter VM IP Address"
      private: no
    - name: "notes"
      prompt: "VM notes"
      private: no
      default: "Deployed with ansible"

  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"

  # Create a VM from a template
  - name: Create CentOS 7 VM in Data Chambers VMware Environment
    vmware_guest:
      hostname: '{{ dc_vc_host }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter: '{{ dc_vc_datacenter }}'
      cluster: '{{ dc_vc_cluster }}'
      folder: '{{ dc_vc_folder }}'
      name: '{{ vmware_hostname }}'
      state: poweredon
      guest_id: rhel7_64Guest
      annotation: "{{ notes }} - {{ creationdate }}"
      use_instance_uuid: true
      disk:
      - size_gb: 60
        type: thin
        datastore: '{{ dc_vc_ds }}'
      networks:
      - name: "{{ dc_vc_port_groups.servernet }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ dc_vc_port_groups.servernet_mask }}"
        gateway: "{{ dc_vc_port_groups.servernet_gw }}"
        dns_servers:
        - 172.16.0.15
        - 192.1.1.15
        start_connected: true
        type: static
        allow_guest_control: true
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
        - 172.16.0.15
        - 192.1.1.15
        domain: '{{ dc_domain }}'
        hostname: '{{ vmware_hostname }}'
      template: '{{ dc_vc_centos_temp }}'
      wait_for_ip_address: yes

```

Expected result is vm creation.  I have tried some different UUID settings but nothing works so far.
