### ISSUE TITLE
Windows Working Group agenda - 2020

### ISSUE THREAD

**Issue by nitzmahone** [ansible/community#517]
[![Github windows issues](https://img.shields.io/github/issues/ansible/ansible/windows.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:windows) [![Github windows PRs](https://img.shields.io/github/issues-pr/ansible/ansible/windows.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:windows) [![Windows agenda](https://img.shields.io/github/issues/detail/last-update/ansible/community/517.svg?label=agenda+update)](https://github.com/ansible/community/issues/420) [![Windows pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/208.svg?label=pinboard+update)](https://github.com/ansible/community/issues/208)

The Windows Working Group is focused on improving Ansible's management of Windows hosts. [We meet every week](https://github.com/ansible/community/wiki/Windows#meetings) on Tuesdays at 20:00 UTC (see [ical](https://raw.githubusercontent.com/ansible/community/master/meetings/ical/windows.ics)) 

More information related to the Windows Working Group is available at:
https://github.com/ansible/community/wiki/Windows

**Feel free to add your questions to this ticket to be discussed during the upcoming meeting.**

After being discussed, raised items are being updated, and after a month resolved items are being hidden from view (but remain accessible).

(migrated from 2019 agenda #420)

**Comment by jhawkesworth** [comment]
It has been a while since we reviewed the WWG meeting time and frequency.  We discussed briefly at WWG on 4th February, but if the current time or date does not suit those who would like to take part, please join WWG irc meeting  next week 11th February 2020 to discuss.

**Comment by jhawkesworth** [comment]
I'd like to discuss https://github.com/ansible/ansible/issues/66804 - is 'warn: no' a generic option for all actions?

**Comment by gundalow** [comment]
## Ansible Contributors Summit EUROPE

## What

Ansible Contributor Summit is a one day event especially for community contributors to meet with each other, as well as Ansible development teams (Core, AWX/Tower, Galaxy) in person, to discuss important issues in the community and help shape the future of Ansible. For those unable to make it to Gothenburg, we welcome you to join virtually for part/all of the day. Online participation and streaming details to follow closer to the summit.

## When
* Contributors Summit: Sunday, 29th March
* Ansible Hackathon: Monday 30th March
* [FOSS-North](https://foss-north.se/2020/): 30 & 31st March

## How

* If you plan to attend **in person**, please register on [Eventbrite](https://www.eventbrite.com/e/ansible-contributor-summit-eu-registration-92039844653)
* If you plan to attend the hackathon or any of FOSS-North please [register](https://foss-north.se/2020/)
* If you plan to attend virtually details will be added to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020) the day before

## Agenda

* Please add suggested topics to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020)
For more info please see the [announcement](https://groups.google.com/forum/#!topic/ansible-devel/o6xnI9g8QqM).

**Comment by RamblingPSTech** [comment]
Module Topic: win_domain_membership
Newbie here. Looking at the module code no changes would be made if the computer was domain joined but lost its trusted relationship with Active Directory. Would it make sense to add some Test-ComputerSecureChannel logic to test and correct the AD trust relationship?

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-computersecurechannel?view=powershell-5.1

**Comment by jhawkesworth** [comment]
A reminder to myself to ask if my community.windows PR is mergeable -  https://github.com/ansible-collections/community.windows/pull/118

**Comment by briantist** [comment]
Finally got around to implementing the `win_environment` dictionary option I mentioned at a previous WWG several months ago
* https://github.com/ansible-collections/ansible.windows/pull/113

**Comment by mhunsber** [comment]
I'd like to discuss if iis modules should be moved to a dedicated collection. There is a lot you can do with IIS that isn't in all of the modules. e.g. [adding a fastcgi module](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/fastcgi/application/) or [configuring client certificate authentication](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/iisclientcertificatemappingauthentication/onetoonemappings/). There are also some modules that could use a lot of improvement. Personally, I use a version of the win_iis_website module that jborean wrote for this pr that never got merged: https://github.com/ansible/ansible/pull/25902 

unless everyone just uses win_dsc?

**Comment by placame** [comment]
Is https://github.com/ansible-collections/ansible.windows/issues monitored?
https://github.com/ansible-collections/ansible.windows/issues/18#issuecomment-707755873

**Comment by briantist** [comment]
* Updated the `win_environment` PR: https://github.com/ansible-collections/ansible.windows/pull/113
* Added small PRs for `win_scheduled_task` and `win_scheduled_task_stat`:
  - https://github.com/ansible-collections/community.windows/pull/167
  - https://github.com/ansible-collections/community.windows/pull/168

* In responding to an issue about `win_psmodule` I described a module I'm using internally that clones registers PSRepositories to other user profiles, to work around the lack of a per-machine repository: 
https://github.com/ansible-collections/community.windows/issues/125#issuecomment-731611082
The module is quite complete functionality-wise. It'd need documentation and tests if it were contributed. Looking to see if there's interest before starting that down road.

To help give an idea, I'm including the spec and some examples:

Examples:
```yaml
- name: "Register CustomRepo"
  community.windows.win_psrepository:
    name: "CustomRepo"
    source_location: "https://nuget.example.com/repo/"
    installation_policy: trusted
    state: present

- name: "Ensure All Users Have CustomRepo Registered"
  community.windows.psget_clone_repository:
    include_system_profiles:
      - 'Local System'
      - 'Local Service'
      - 'Network Service'
    repos_when_missing:
      - PSGallery
      - CustomRepo
    repos_when_updating:
      - CustomRepo

- name: "Ensure SpecialSvcAcct and Administrator Have OtherRepo Registered"
  community.windows.psget_clone_repository:
    include_users:
      - SpecialAvcAcct
      - Administrator
    repos_when_missing:
      - PSGallery
      - OtherRepo
    repos_when_updating:
      - OtherRepo
```

```powershell
$spec = @{
    supports_check_mode = $true
    options = @{
        source = @{
            type = 'path'
            default = '%LOCALAPPDATA%\Microsoft\Windows\PowerShell\PowerShellGet\PSRepositories.xml'
        }
        include_system_profiles = @{
            type = 'list'
            elements = 'str'
            default = @()
        }
        include_users = @{
            type = 'list'
            elements = 'str'
            default = @(
                '*'
            )
        }
        exclude_users = @{
            type = 'list'
            elements = 'str'
            default = @(
                'All Users'
                'Public'
            )
        }
        repos_when_missing = @{
            type = 'list'
            elements = 'str'
            default = @(
                'PSGallery'
            )
        }
        repos_when_updating = @{
            type = 'list'
            elements = 'str'
            default = @()
        }
    }
}
```
