### ISSUE TITLE
Unable to connect: unsupported protocol (_ssl.c:897)

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/community#523]
Hi,

I am unable to connect to vSphere 5.5.0 from Centos 8 with Python 3 intepreter "/usr/libexec/platform-python" in a virtual environment (AWX).

```
- name: Create new VMware Virtual Machine
  vmware_guest:
    hostname: "{{ hostname }}"
    esxi_hostname: "{{ esxi_hostname | default('minasanor.localdomain') }}"
    username: '{{ domain_user }}'
    password: "{{ domain_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    name: "{{ vm_name }}"
    folder: "{{ vm_destination | default('/Test-Dev/QA') }}"      
    state: poweredon
    disk:
    - size_gb: '{{ disk_size | default(40) }}'
      type: thin
      autoselect_datastore: True
    hardware:
      memory_mb: "{{ memory | default(4096) }}"
      num_cpus: "{{ cores | default(2) }}"
      num_cpu_cores_per_socket: "{{ cores | default(2) }}"
    networks:
    - name: LAN
      domain: "{{ domain }}"
      dns_servers:
      -  "{{ dns1 }}"
      -  "{{ dns2 }}"
      type: static
      ip: "{{ new_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"
    customization:
      autologon: True
      hostname: "{{ vm_name }}"
      domain: "{{ domain }}"
      fullname: "{{ local_user }}"
      password: "{{ local_password }}"
      domainadmin: "{{ domain_user }}"
      domainadminpassword: "{{ domain_password }}"
      joindomain: "{{ domain }}"
      timezone: 105
      runonce:
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\StartupScripts\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      - netsh advfirewall set allprofiles state off
    wait_for_customization: yes
    template: "{{ template }}"
    wait_for_ip_address: yes
```

```
Unable to connect to vCenter or ESXi API at virtualcenter.localdomain on TCP/443: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897)
```

The error seems to be related to pyvmomi module itself. 

I am using ansible module vmware_guest with ansible > 2.9.X

Digging around and it might have something to do with TLS but not sure.

When using my local environment with Ubuntu 19.10 no errors occur!

Does anybody know a fix for this?
